package: uploader
version: '3.0.0-dev'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/uploader

requires:
    php:
        version: '>=8.1'
    redaxo: ^5.18.0

page:
    title: translate:uploader_title
    perm: uploader[page]
    pjax: true
    icon: rex-icon fa-upload
    subpages:
        upload: {title: translate:uploader_title}
        settings: {title: translate:settings, perm: admin}

pages:
    mediapool/upload:
        title: translate:uploader_title
        perm: uploader[]

