package: uploader
version: '2.4.3'
author: 'Friends Of REDAXO'
supportpage: 'https://github.com/FriendsOfREDAXO/uploader'

page:
    title: 'Uploader'
    icon: rex-icon rex-icon-import
    subpages:
        settings:
            title: 'Settings'
            perm: admin
        upload:
            title: 'Upload'
        endpoint:
            title: 'endpoint'
            hidden: true
            hasLayout: false
requires:
    redaxo: '^5.1.0'

endpoint: 'index.php?page=uploader/endpoint'

