package: uploader
version: '2.7.0'
author: 'Friends Of REDAXO'
supportpage: 'https://github.com/FriendsOfREDAXO/uploader'

page:
    title: 'Uploader'
    icon: rex-icon rex-icon-import
    pjax: true
    subpages:
        settings:
            title: 'translate:page_settings'
            perm: admin
        upload:
            title: 'translate:page_upload'
        bulk_rework:
            title: 'translate:page_bulk_rework'
            perm: uploader[bulk_rework]
        endpoint:
            title: 'endpoint'
            hidden: true
            hasLayout: false
requires:
    redaxo: '^5.16.0'

endpoint: 'index.php?page=uploader/endpoint'

